### ISSUE TITLE
[Working] Refactor: Data abstraction, Middleware and State management

### ISSUE THREAD

**Issue by ShirleyMatrix** [Raka-loah/Paarthurnax#102]
### Part 1 
目前为止，老帕已经经历过多次重构，项目也变得更加结构化。
但是大部分重构仅仅停留在代码结构组织层面，老帕的核心流程与开始时没有太大改变，即：

- 以线性流程进行的，接受消息(message)-简单的消息预处理-分发消息-执行动作(actions)-数据的后处理-返回消息。
- 数据流从接收到分发阶段依赖于接受消息的结构，执行动作后的返回值完全取决于动作自身，向内和向外的数据流是分开的。

这样就带来了几个问题：
1. 动作执行阶段获取的**消息结构**严重依赖于发送者的具体的实现细节，而非抽象。

对于插件的编写者来说，需要去理解接口解析的数据的细节（目前来说也就是onebot），并且接口发生比较大变动时，对插件来说无疑是毁灭性的，对项目本身来说也是（当然目前来看接口本身改动的可能性不是很大）

所以我建议新增一个message数据类，将message作为一个type对待，对message进行封装，映射为自己定义的消息结构，并内建一些实用方法，如空值检查，数据结构格式化，消息类型判断等。

通过对这种封装来隐藏message的实现细节，插件开发者不再需要去关心消息细节，而消息接口的变动只需要通过简单的重写message类对数据进行重新的映射

目前可以简单的跟onebot的接口同构，同时新增一些字段，实现对数据的扁平化处理。对于部分不能保证存在的数据也可以进行简单的处理保证不会遇到报错。

``` python

#e.g.  
# app.py
def post():
    try:
        # POSTed data as json
        # j = request.get_json(force=True)
        j = new Message(request.get_json(force=True))

# Paarthurnax/plugins/p_misc/misc.py
def msg_stella(j):
    msg = ''
    bot_role = ''
    # if j['message_type'] == 'group':
    if j.isGroup():
    # xxx
```

2. 后处理阶段和返回消息阶段只能拿到没有保证的数据。

在整个流程里，前面处理的数据流message（在项目里一般是以`j`来代表）在动作处理阶段就不再往下传递了，之后的数据流改为了由action返回的值，目前是基于action具体实现的msg，以及部分state code。

这里的问题跟前面类似，后处理阶段处理的数据要么是根据从预处理阶段获取到的信息，要么是由action自身决定实现决定的msg，后者需要依赖于具体action的实现。

并且插件里的实现都是通过自行执行代码实现，拥有无限权限，安全性无法保证。

解决方法与上面的方式类似，将动作的执行部分抽离出来单独存在。插件仅仅负责生成一种中间结构，将中间结构交由动作的执行器处理。这样我们就可以对插件的独立性和安全性进行保证。

```python
#e.g.
#简单的执行器实现
# param: aciton
# action:{
#    type:'sendMsg', //动作的类型，发送消息，设定定时事件，写入指令等
#    content:' some message' //动作的内容
#    //更多的字段
#}
def exec(action):
    switch(action.type):
        case ...
# 插件实现
def sendSomeMessage():
    msg = 'hello,my name is  Paarthurnax'
    return {
        type:'sendMsg' ,
        content:msg
    }
```

总的来说，产生上面两个问题的原因是因为在分离插件实现过程中，仅在代码结构方面进行的分离，而传递消息方面没有真正的分离，导致了高度的耦合性。通过产生并传递中间结构，产生真正的解耦合。

### Part 2

现在换个角度，从一个比较宏观的角度去审视老帕。

从语言应用的角度看，仅就执行命令而言，老帕是以python-flask为宿主环境，使用一种极其简单的命令式、交互式的指令语言，处于REPL模式下运行的解释器。

在这个角度下，简单方面，可以对输入信息进行简单的语法分析，最简单的情况下可以仅解析 program := command arg* 这种形式，更进一步扩展可以支持--option 以及语法缩写等，甚至于单独实现一个简单的命令式语言（比如叫:Thuum ：）并将部分pythonAPI封装作为宿主环境的API等等。

其实大家也基本都是差不多类似结构，下至计算器，上至服务器，数据库。老帕就很像一个简单server实现，只不过是flask帮忙完成网络传输和http数据解析以及返回（超级套娃）。在交互方面与各种前端设计也类似，只不过交互手段从输入设备变为了指令。

所以老帕也可以从其他服务端框架，以及前端框架方面借鉴一些设计。

下面就是从其他方面借鉴而来

3.消息处理环节是线性的，扩展不灵活。 

消息处理环节，类似于一个简单的服务端框架，解析指令环节类似url的解析，而分发消息环节就是router，而onebot就是一种简单的消息协议。

但是目前这个消息处理环节扩展性很差，通过顺次对j进行读写，每次增加新的环节都需要理解整个流程，并依赖于前面环节。
还有数据流是中断的，前面的message数据流止于action，后处理看不到被action处理过的message.

我们可以参考koa的设计，将顺序结构改为级联结构，通过函数的级联调用来处理信息流。并且通过上述描述的message封装更进一步，将输入流和输出流合并为上下文对象，让全流程都可以对输入流输出流进行读写。
```python
# 原本结构
j = get()
check(j)
invite(j)
bannerCheck(j)
Preprocessors(j)
Logs(j)
msg = dispatch(j)
format(msg)
send(msg)

# 级联结构
# ctx {
#   req{
#       message{},
#       action
#   }   
#   res{}
# }

def parser(ctx,next):
    ctx.req.message = new Message(ctx.j)
    next()

def Logs(ctx,next):
    print '->' + ctx.req.message
    next()
    print '<-' + ctx.res.message

def exector (ctx,next):
    next()
    ctx.req.action.result = exec(ctx)

def send(ctx,next):
    next()
    ctx.res.message = ctx.req.action.result

dragon.use([parser,Logs,exec,send ...])

# => send(ctx,exector(ctx,Logs(ctx,parser(ctx,next)))  next = () => {}
# 执行流： send::next() = > exector::next() => Logs::'->' => Logs::next() =>
# parser::ctx.req.message => parser::next() => Logs::'<-' => exector::exec() => send::ctx.res.message

dragon.hear(j)
```

4.缺乏全局的状态管理。

WORKING: 出去买个菜.

**Comment by Raka-loah** [comment]
对于Python版的老帕，目前的写法是有意而为之，而且……`j['message']` 改成一个类无非就变成了 `j.message` ……就很……尬。
CQHTTP各项群管API会在后期进入`Talking_Dragon`类，即禁言等操作不再需要单独由插件POST到平台。同时消息记录也会有专门的query API。
Ps. 线性的处理模式实际上就是wow的oUF头像插件的处理模式（我写oUF布局所以对这个模式非常熟悉），实际上是够用的，wow那么多oUF头像插件可以证明这一点。
最cool的方案是用go写本体，lua作为插件逻辑实现，可以搞定以上一切问题，但目前没有这个打算，因为何必呢……

**Comment by ShirleyMatrix** [comment]
有意是指，onebot的协议？
写成类可以把那些跟数据有关的操作封装到类里面，最基本的像是写入读取，避免无意之间修改了数据。再有就是那些对数据自身的操作，验证啥的，还能控制插件了解到的消息。最主要还是**解除耦合**，进行抽象啥的，**方便移植**,比如移植到一个不支持onebot协议平台上，只需要简单的重写message重新做一下映射就好了，不需要整个重写。
比如我要是现在编写一个插件，我需要去自行去解析数据，然后还需要了解onebot传递了消息结构，尤其是有些key是不保证一定有值的。与其是让插件自己去依赖具体实现细节的判断`j['message_type'] == 'group' ` 不如提供api去确定`j.isGroup`

我还是觉得别让插件直接去操纵api，而是生成做什么的指令，然后让一个受控的执行器去执行就好了啦，（这比较偏向于传统编译器的结构）这样可以组成消息队列，能去控制执行时机和顺序，然后进行**缓存优化**，比如对于近1s内所有比如10次的 每日特惠指令 ，可以合并成一次查询

生命在于折腾，够用可不行😈

**Comment by Raka-loah** [comment]
> 有意是指，onebot的协议？

OneBot就是CQHTTP，即CQ跑路后目前可能唯一的机器人HTTP API事实标准，老帕故意往简化/不灵活的流程上面做是因为OneBot（CQHTTP）的SDK已经tmd太多了：[OneBot生态](https://github.com/howmanybots/onebot/blob/master/ecosystem.md#sdk%E5%BC%80%E5%8F%91%E6%A1%86%E6%9E%B6)

实际上老帕的各项功能是可以直接移植到[Nonebot](https://github.com/nonebot/nonebot)上面的，人家是现代化的、有效利用decorator的**老帕原本就应该写成这样的**框架（包括其他同类框架基本上都是这样），但老帕是一个从[QQbot](https://github.com/pandolia/qqbot)时代一直走过来的legacy屎山，真正意义上的重构会把它重构成Nonebot，那就不如直接用Nonebot。目前老帕使用的这些格式，还是从当初 `if...else...` 时代遗留下来的格式

> 与其是让插件自己去依赖具体实现细节的判断j['message_type'] == 'group' 不如提供api去确定j.isGroup

这更是有意的，思考一下，如果OneBot突然改变了 `message_type` 的返回值，导致插件逻辑失效，此时老帕变得不好使是谁的原因？

因为OneBot没有做好兼容旧版，同时**插件作者没有去及时更新**，老帕只是无辜的二传手。

如果老帕实现了对整个消息类的二次包装，此时 `isGroup` 失效是谁的原因？

因为OneBot没有做好兼容旧版，同时**我没有去及时更新老帕的消息类二次包装**。

通过这种设计，就把维护成本**转嫁到了插件作者那里**。計画通り（微笑

> 还有数据流是中断的，前面的message数据流止于action，后处理看不到被action处理过的message

前期有意为之，后处理只作为bot command未触发的补充，目前正在考虑是否统一处理流程。

> 别让插件直接去操纵api，而是生成做什么的指令，然后让一个受控的执行器去执行

运行老帕的电脑上一定会有个Python解释器，只要还是.py写插件，老帕就可以随意被绕过……你甚至可以让老帕调用你的.py来kill掉老帕然后跑一个自己的新bot框架，这个bot框架可以叫 `dragonslayer` 😂

解决这个问题的方法，就是让逻辑实现不使用.py，同时还能完善地实现各种逻辑，此时最常见的方法果然还是Lua……即老帕往Lua暴露几个特定API，然后老帕eval一下来获取返回值，就还是WOW的插件那一套，这样就完全实现了权限可控，且逻辑方便书写，然后问题又来了，为了这个破事再去学一下Lua？这时候老帕就变成了纯种的flask app，马上会有人告诉你Go+Gin不香吗……天生跨平台还高效率。

**总结**：老帕最重要的部分实际上并不是HTTP框架的实现，而是Warframe世界状态的解析。实际上，除了QQ这个死活不开放API的IM之外，没有哪个开放API的IM的bot会用HTTP跨进程通讯这种方式脱裤子放屁（因为当初各种bot平台都是自己用.dll在自立门户，甚至有了[Newbe.Mahua](https://github.com/newbe36524/Newbe.Mahua.Framework)这种写一次编译到各种bot的插件框架，由于上手难度高，最后CQHTTP这种不限制语言的才成为萌新首选）。例如Discord就有用Python写成的Bot叫做[Red](https://github.com/Cog-Creators/Red-DiscordBot)，此时仅需要把老帕的Warframe部分复制过去，利用Red的Cogs机制引用就是移植成功，而老帕HTTP的部分其实可以完全抛弃，这也是这次重构的初衷，只是为了让我自己好写一点。

但是MIT协议没有阻拦任何人去fork老帕哦( ͡° ͜ʖ ͡°)

**Comment by ShirleyMatrix** [comment]
_（那一开始就不打算实现一个框架为啥不直接用现成的，专心开发无法插件不好吗🤣）_

执行器那里，审核起来方便，名义上不允许直接操纵py环境，只能返回执行命令，这样审核起来方便一点，不然不好分辨是必要的操作还是恶意的操作

都丢给插件开发者，插件开发者要骂人了辣，到时候一不维护，新老插件就不兼容了

那我去试试自己弄一个框架好了，到时候邀请你来开发wf插件（

那就close了
